language: python
python:
  - 2.7

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - flake8
  - py.test

after_success:
  - coveralls

sudo: false

matrix:
  fast_finish: true
